### ISSUE TITLE
undefined method after update from version 0.5.6 to 2.1.1 

### ISSUE THREAD

**Issue by dbachinin** [huacnlee/rails-settings-cached#186]
Hi! After update rails-settings-cached, I receive error ```NoMethodError: undefined method `twilio_voice' for #<Class:0x0000562f34344298>``` when trying call old scoped method.
Old migration:
```
  def self.up
    create_table :settings do |t|
      t.string  :var,        null: false
      t.text    :value,      null: true
      t.integer :thing_id,   null: true
      t.string  :thing_type, null: true, limit: 30
      t.timestamps
    end

    add_index :settings, %i(thing_type thing_id var), unique: true
```
Model:

```
class Settings < RailsSettings::Base
  cache_prefix { "v1" }

  # Define your fields
  # field :foo, type: :string, default: "http://localhost:3000"
  # field :default_locale, default: "en", type: :string
  # field :confirmable_enable, default: "0", type: :boolean
  # field :admin_emails, default: "admin@rubyonrails.org", type: :array
  # field :omniauth_google_client_id, default: (ENV["OMNIAUTH_GOOGLE_CLIENT_ID"] || ""), type: :string, readonly: true
  # field :omniauth_google_client_secret, default: (ENV["OMNIAUTH_GOOGLE_CLIENT_SECRET"] || ""), type: :string, readonly: true
end
```

**Comment by huacnlee** [comment]
>  BREAK CHANGES WARNING: rails-settings-cached 2.x has redesigned the API, the new version will compatible with the stored setting values by an older version. When you want to upgrade 2.x, you must read the README again, and follow guides to change your Setting model. 0.x stable branch: https://github.com/huacnlee/rails-settings-cached/tree/0.x
